version: '2'
services:
  vcf2neo:
    restart: always
    build: .
    image: vcf2neo
    container_name: vcf2neo
    environment:
      DB: db
    depends_on:
      - db
  db:
    image: neo4j:3.0.4
    container_name: vcf2neo-db
    environment:
      NEO4J_AUTH: none
    ports:
      - "7687:7687"
      - "7474:7474"
